parameters:
  - name: terraformWorkingDirectory
    type: string

steps:
  # Terraform Init
  - task: Bash@3
    displayName: 'Terraform Init'
    inputs:
      targetType: 'inline'
      script: |
       cd ${{ parameters.terraformWorkingDirectory }}
       terraform init $(terraformBackendConfig)
  
  # Terraform validate
  - task: Bash@3
    displayName: 'Terraform Validate'
    inputs:
      targetType: 'inline'
      script: |
       cd $(terraformWorkingDirectory)
       terraform validate $(terraformBackendConfig)

  # Terraform plan
  - task: Bash@3
    displayName: 'Terraform Plan'
    inputs:
      targetType: 'inline'
      script: |
       cd ${{ parameters.terraformWorkingDirectory }}
       terraform plan -out=tfplan -input=false $(terraformInputVariables)

  # Terraform destroy
  - task: Bash@3
    displayName: 'Terraform Destroy'
    inputs:
      targetType: 'inline'
      script: |
       cd ${{ parameters.terraformWorkingDirectory }}
       terraform destroy \
          -input=false \ 
          -auto-approve \
          $(terraformInputVariables)
  