parameters:
  - name: TerraformWorkingDirectory
    type: string
  - name: TFVarsFileNameLocation
    type: string

steps:
  # Terraform Init
  - task: Bash@3
    displayName: 'Terraform Init'
    inputs:
      targetType: 'inline'
      script: |
       cd ${{ parameters.TerraformWorkingDirectory }}
       terraform init $(TerraformBackendConfig)
  
  # Terraform validate
  - task: Bash@3
    displayName: 'Terraform Validate'
    inputs:
      targetType: 'inline'
      script: |
       cd ${{parameters.TerraformWorkingDirectory }}
       terraform validate

  # Terraform plan
  - task: Bash@3
    displayName: 'Terraform Plan'
    inputs:
      targetType: 'inline'
      script: |
       cd ${{ parameters.TerraformWorkingDirectory }}
       terraform plan \
        -out=tfplan \
        -var-file="${{ parameters.TFVarsFileNameLocation }}" \
        -input=false $(TerraformInputVariables)
  

  # Terraform destroy
  - task: Bash@3
    displayName: 'Terraform Destroy'
    inputs:
      targetType: 'inline'
      script: |
       cd ${{ parameters.TerraformWorkingDirectory }}
       terraform destroy \ 
          -auto-approve \
          -input=false $(TerraformInputVariables) \ 
          -var-file="${{ parameters.TFVarsFileNameLocation }}" \       
          
