parameters:
  - name: terraformWorkingDirectory
    type: string

steps:
  # Terraform Init
  - task : Bash@3
    displayName: Terraform Init
    inputs:
      targetType: 'inline'
      script: |
        echo "Terraform Init"
        cd ${{ parameters.terraformWorkingDirectory }}
        terraform init $(TerraformBackendConfig)

  # Terraform validate
  - task : Bash@3
    displayName: Terraform Validate
    inputs:
      targetType: 'inline'
      script: |
        echo "Terraform Validate"
        cd ${{ parameters.terraformWorkingDirectory }}
        terraform validate
        
  # Terraform Plan
  - task : Bash@3
    displayName: Terraform Plan
    inputs:
      targetType: 'inline'
      script: |
        echo "Terraform Plan"
        cd ${{ parameters.terraformWorkingDirectory }}
        terraform plan -out=tfplan -input=false $(terraformInputVariables)  
  
  # Terraform Apply
  - task : Bash@3
    displayName: Terraform Apply
    inputs:
      targetType: 'inline'
      script: |
        echo "Terraform Apply"
        cd ${{ parameters.terraformWorkingDirectory }}
        terraform apply -auto-approve tfplan
