steps:
  - task: Bash@3
    displayName: Clean workspace
    condition: always()
    inputs:
      targetType: 'inline'
      script: |
        rm -rf $(Build.SourcesDirectory)/*
        ls -la $(Build.SourcesDirectory)
        echo "Workspace cleaned."
