variables:
  ###########
  # General #
  ###########
  # Project Name
  - name: projectName
    value: cicd-corp    

  ###################
  # ADO Agent Pools #
  ###################
  # Agent Pool for Dev
  - name: DevAgentPool
    value: Default    
  # Agent Pool for Prod
  - name: ProdAgentPool
    value: ec2_prod_agent_pool_ado

  ####################
  # ADO Environments #
  ####################    
  # ADO Environment for Dev
  - name: DevAdoEnvironmentName
    value: Dev_Usa
  # ADO Environment for Prod
  - name: ProdAdoEnvironmentName
    value: Prod_Usa
  
  #######
  # AWS #
  #######
  # AWS Region for Dev
  - name: AwsDevRegion
    value: us-east-1    
  # AWS Region for Prod
  - name: AwsProdRegion
    value: us-east-1    

  #############
  # Terraform #
  #############
  # Terraform Backend Deployment
  - name: TFBucketStateDev
    value: cicd-corp-terraform-state-dev    
  - name: TFDynamoDBTableDev
    value: cicd-corp-terraform-state-lock-dev    
  # Terraform Backend Production
  - name: TFBucketStateProd
    value: cicd-corp-terraform-state-prod    
  - name: TFDynamoDBTableProd
    value: cicd-corp-terraform-state-lock-prod    
  # Terraform Working Directory for Setup
  - name: TerraformSetupWorkingDirectory
    value: infra/terraform/infra-setup        
  # Terraform Working Directory for Service
  - name: TerraformServiceWorkingDirectory
    value: infra/terraform/infra-service    
  
