#################
# Set up deploy #
#################

# Trigger automatically on changes to the development branch
trigger:
  branches:
    include:
      - development
  paths:
    exclude:
      - infra/deploy
# No pull request trigger
pr: none

# Parameters for the pipeline
parameters:
  - name: poolName
    type: string
    default: Default
    values:
      - Default
      - test_ec2_agent_ado
  - name: environmentName
    type: string
    default: dev
    values:
      - dev
      - test
      - prod
stages:
  - stage: deploy_setup_dev
    displayName: Deploy Setup Dev
    pool:
      name: ${{ parameters.poolName }} 
    # variables:
      # link azure devops variable group
      # link environment 
      # link terraform input variables
      # - template: ../vars/terraform-input variables.yml
    jobs:
      - job: deploy_setup_dev
        displayName: Deploy Setup Dev
        steps: 
          # Terraform deployment
          # - template: ../steps/terraform/terraform-deploy-steps.yml
          # Clean workspace
          ${{ if or(eq(parameters.environmentName, 'dev'), eq($(Build.SourceBranchName), 'refs/heads/development')) }}:
            - task: bash@3
              displayName: Clean workspace
              inputs:
                targetType: 'inline'
                script: |
                    echo "Deploying into test environment..."
                    echo "Branch name: $(Build.SourceBranchName)"
                    echo "Env: $(environmentName)"
              

