#################
# Set up deploy #
#################

# Trigger automatically on changes to the development branch
trigger:
  branches:
    include:
      - development
  paths:
    exclude:
      - infra/deploy
# No pull request trigger
pr: none

# Parameters for the pipeline
parameters:
  - name: poolName
    type: string
    default: Default
    values:
      - Default
      - test_ec2_agent_ado
  - name: environmentName
    displayName: |
      Environment to deploy. (Note: test and prod environment only works when the branch is main)
    type: string
    default: dev
    values:
      - ${ if eq(variables['Build.SourceBranchName'], 'development') }:
        - dev
      - ${ if eq(variables['Build.SourceBranchName'], 'main') }:        
        - poc
        - prod
stages:
  - stage: deploy_setup_dev
    displayName: Deploy Setup Dev
    pool:
      name: ${{ parameters.poolName }} 
    jobs:
      - job: deploy_setup_dev
        displayName: Deploy Setup Dev
        steps: 
          # Clean workspace
          - ${{ if or(eq(parameters.environmentName, 'dev'), eq(variables['Build.SourceBranchName'], 'development')) }}:
              - task: Bash@3
                displayName: Dummy task
                inputs:
                  targetType: 'inline'
                  script: |
                    echo "Deploying into test environment..."
                    echo "Branch name: $(Build.SourceBranchName)"
                    echo "Env: ${{ parameters.environmentName }}"
          - ${{ else }}:
              - task: Bash@3
                displayName: Dummy task production
                inputs:
                  targetType: 'inline'
                  script: |
                    echo "Deploying into production environment..."                    

