stages:
  - stage: deploy_infra_setup_dev
    displayName: Deploy infra Setup into Dev
    pool:
      name: $(DevAgentPool)
    variables:
      # link variables per environment
      - template: ../vars/dev/dev-usa-vars.yml
      # link terraform backend configuration for dev
      - template: ../vars/terraform/terraform-backend-configuration.yml
        parameters:
          TFS3BucketName: $(TFBucketStateDev) # S3 bucket name for managing state
          TFDynamoDBTableName: $(TFDynamoDBTableDev) # DynamoDB table name for managing lock
      # link terraform input variables
      - template: ../vars/terraform/terraform-input-variables.yml
    jobs:
      - job: deploy_setup_dev
        displayName: Deploy Infra Setup into Dev
        steps: 
          # Terraform deployment
          - template: ../steps/terraform/terraform-deploy-steps.yml
            parameters:
              TerraformWorkingDirectory: $(TerraformSetupWorkingDirectory) # Terraform files location
              TFVarsFileNameLocation: $(TFVarsFileNameLocation) # TFVars file location for dev
          # Clean workspace
          - template: ../steps/utils/clean-workspace.yml
            
