parameters:
  - name: poolName
    type: string
    default: '$(poolName)'

stages:
  - stage: deploy_setup_dev
    displayName: Deploy Setup Dev
    pool:
      name: ${{ parameters.poolName }}
    variables:
      # link azure devops variable group
      # link environment 
      # link terraform input variables
      - template: ../vars/terraform-input variables.yml
    jobs:
      - job: deploy_setup_dev
        displayName: Deploy Setup Dev
        steps: 
          # Terraform deployment
          - template: ../steps/terraform/terraform-deploy-steps.yml
          # Clean workspace
            
