variables:
# General
- name: environment
  value: dev-usa
# AWS
- name: awsRegion
  value: $(AwsDevRegion)
# Terraform
- name: TFVarsFileNameLocation
  value: infra/terraform/infra-setup/dev/dev.tfvars
