parameters:
  - name: TFS3BucketName
    type: string
  - name: TFDynamoDBTableName
    type: string

variables:
  TerraformBackendConfig: |
    -backend-config="region=$(awsRegion)" \
    -backend-config="bucket=${{ parameters.TFS3BucketName }}" \
    -backend-config="key=$(projectName)/setup/tf-state-setup" \
    -backend-config="path=backend-config.tf" \
    -backend-config="dynamodb_table=${{ parameters.TFDynamoDBTableName }}" \
    -backend-config="encrypt=true"
