#################
# Set up deploy #
#################

# Manual trigger
trigger: none
# No pull request trigger
pr: none

# Parameters for the pipeline
parameters: 
  - name: environmentNameToDeploy
    displayName: Environment to deploy.
    type: string
    default: dev
    values:
        - dev    
        - prod
variables:
  # Link global variables
  - template: ../../shared/vars/global-shared-variables.yml

stages:
 # Clean workspace
  - ${{ if eq(parameters.environmentNameToDeploy, 'dev') }}:
      - template: ../stages/deploy-dev-stage.yml
  - ${{ else }}:
      - template: ../stages/deploy-prod-stage.yml   

