# Destroy setup pipeline #

# Manual trigger
trigger: none
# No pull request trigger
pr: none

# Parameters for the pipeline
parameters:
  - name: environmentNameToDestroy
    displayName: Environment to destroy.
    type: string
    default: dev
    values:
        - dev    
        - prod
variables:
  # Link global variables
  - template: ../../shared/vars/global-shared-variables.yml

stages:
  - if{{ eq(parameters.environmentNameToDestroy, 'dev') }}:
    - stage: Destroy_Setup_Destroy_Stage
      displayName: Destroy Setup ${{ parameters.environmentNameToDestroy }}
      pool:
        name: $(TestAgentPool)
      jobs:
        - job: Destroy_Setup_Destroy_Job
          displayName: Destroy Setup ${{ parameters.environmentNameToDestroy }}
          steps: 
            # Terraform destroy
            - template: ../steps/terraform/terraform-destroy-steps.yml
            # clean workspace
            - template: ../steps/clean-workspace.yml
  - ${{ else }}:
    - stage: Destroy_Setup_Destroy_Stage
      displayName: Destroy Setup ${{ parameters.environmentNameToDestroy }}
      pool:
        name: $(ProdAgentPool)
      jobs:
        - job: Destroy_Setup_Destroy_Job
          displayName: Destroy Setup ${{ parameters.environmentNameToDestroy }}
          steps: 
            # Terraform destroy
            - template: ../steps/terraform/terraform-destroy-steps.yml
            # clean workspace
            - template: ../steps/clean-workspace.yml
