#################
# Set up deploy #
#################

# Manual trigger
trigger: none
# No pull request trigger
pr: none

# Parameters for the pipeline
parameters: 
  - name: EnvironmentNameToDeploy
    displayName: Environment to deploy.
    type: string
    default: dev
    values:
        - dev    
        - prod
  - name: InfraToDestroy
    displayName: 'Infrastructure to destroy'
    type: string
    values:
        - infra_setup
        - infra_service
variables:
  # Link global variables
  - template: ../../shared/vars/global-shared-variables.yml

stages:
  - template: ../stages/destroy-infra.yml
    parameters:
      EnvironmentNameToDeploy: ${{ parameters.EnvironmentNameToDeploy }}

