# Destroy setup pipeline #

# Manual trigger
trigger: none
# No pull request trigger
pr: none

# Parameters for the pipeline
parameters:
  - name: poolName
    displayName: |
      Pool name to use.
    type: string
    default: Default
    values:
      - Default
      - test_ec2_agent_ado
  - name: environmentName
    displayName: |
      Environment to deploy.
    type: string
    default: dev
    values:
        - dev    
        - poc
        - prod
variables:
  # Link global variables
  - template: ../../shared/vars/global-variables.yml

stages:
  - stage: Destroy_Setup_Stage
    displayName: Destroy Setup ${{ ]parameters.environmentName }}
    pool:
      name: ${{ parameters.poolName }}
    jobs:
      - job: Destroy_Setup_Job
        displayName: Destroy Setup ${{ parameters.environmentName }}
        steps: 
          # Terraform destroy
          - template: ../steps/terraform/terraform-destroy-steps.yml
          # clean workspace
          - template: ../steps/clean-workspace.yml
